### PR TITLE
See #9 - Add the database Catalog to all csvs

### PR DESCRIPTION
**Pull request by sualeh**
@adriens - please see if this fixes your issue

### CODE REVIEW

**Comment by adriens** [comment]
WOW, thanks a lot @sualeh , I'll give it a try while releasing on the latest schemacrawler version you just released yesterday 👍

**Comment by sualeh** [comment]
@adriens - did this work for you?

**Comment by adriens** [comment]
I could even not give it a try, I was very busy on we side projects. New ELK has been released, I intend to work on this topic in the same time

**Comment by adriens** [comment]
Waiting for the new interface for schemacrawler to get database name, see #9

**Pull request closed without merging**
